### ISSUE TITLE
add tag to on topic list.

### ISSUE THREAD

**Issue by jsroyal** [spring-guides/tut-bookmarks#27]
Before the added tags on topic page
![screenshot from 2017-02-07 17-43-41](https://cloud.githubusercontent.com/assets/10773353/22690782/645212cc-ed5d-11e6-8ca0-a0f2e682d78b.png)
After the added tags on topic page
![screenshot from 2017-02-07 17-44-33](https://cloud.githubusercontent.com/assets/10773353/22690783/6456987e-ed5d-11e6-8729-c64efb72a7c0.png)
Consider as PR.

**Comment by gregturn** [comment]
Interesting. I wasn't aware of github tags. Not sure of the benefits, yet, and given we have 60+ guides and at least three other tutorials, I would want to apply an even handed approach to doing this.

**Comment by jsroyal** [comment]
@gregturn Yeah! It is interesting.
This feature added last week on github.
It is great feature to discover repo according topic/tags.
Also explore more thing about it [Here is link](https://github.com/blog/2309-introducing-topics)

**Comment by jsroyal** [comment]
![screenshot from 2017-02-08 01-03-46](https://cloud.githubusercontent.com/assets/10773353/22707990/a2fa47e6-ed9a-11e6-88c7-915c85af36d7.png)
We can add all this tags and topic on this feature.

**Comment by jsroyal** [comment]
Hello @gregturn,
I'm fresher to here and want explore Spring Framework.
Is there any advice being expertise at Pivotal (home of Spring)?  
excited to learning about it.

**Comment by gregturn** [comment]
I'd suggest reading our 60+ guides (30 minute lessons) at spring.io/guides. There are also some tutorials at the bottom. 

For now I'm going to close this ticket since I don't think GitHub tags are if current benefit.

**Comment by jsroyal** [comment]
@gregturn why do you think tags are not benefits?
Is there any thoughts? 
Can I work on it?
What do you mean 30 minutes lessons?

**Comment by gregturn** [comment]
Every guide at http://spring.io/guides is kept small enough to be tackled in a lunch break ie 30 minutes. So if you want an intro to Spring id start there. 

We embed asciidoctor tags in all these guides so that on the website, they are navigable. Replicating the same information in GitHub won't produce anything on the site, the target location for consuming this material (notice how we use macros that don't resolve on GitHub?). And duplicating the tags introduces a new requirement for any new guides in the future that I see little benefit.

**Comment by jsroyal** [comment]
>Every guide at http://spring.io/guides is kept small enough to be tackled in a lunch break ie 30 minutes. So if you want an intro to Spring id start there.

@gregturn Thanks for tips.
